server:
  port: 8088
  servlet:
    context-path: /api/v1

spring:
  application:
    name: AUTH-SERVICE
  config:
    import: configserver:http://localhost:9296
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/user_service_db
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
